data_pipeline:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: dbt_db
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: dbt_role
      schema: dbt_schema
      threads: 10
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse: dbt_wh
  target: dev
